services:
  db:
    image: postgres:14
    container_name: local_todo_db
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - local_todo_pg_vol:/var/lib/postgresql/data

volumes:
  local_todo_pg_vol:
