name: hotwire-todo-compose
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
    command: bundle exec sidekiq -C config/sidekiq.yml && bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    networks:
      - database
    depends_on:
      - db

  redis:
    image: redis:alpine3.20
    ports:
      - "6379:6379"
    networks:
      - database

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database

networks:
  database:
    driver: bridge

volumes:
  postgres_data:
