name: hotwire-todo-compose
services:
  # web:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - SECRET_KEY_BASE=dummy
  #     - DATABASE_URL=postgres://hotwire_todo:postgres@db:5432/hotwire_todo
  #   volumes:
  #     - .:/myapp
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - database
  #   depends_on:
  #     - db

  redis:
    image: redis:alpine3.20
    ports:
      - "6379:6379"
    networks:
      - database

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: hotwire_todo
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotwire_todo
      POSTGRES_HOST: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database

networks:
  database:
    driver: bridge

volumes:
  postgres_data:
